Next/version (#20)
* next version should be 1.0.0-rc6

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* updated examples

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* madification to hierarchie

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* always use semicolons when using my code

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* correction

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* [airbnb/javascript]

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* Why?

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* always use semicolons

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* on behalf of which the API client is authorized

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* correction

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removed file from unused files

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* Version/feature axio mock (#18)

* splited axiosApi ✨  Done in 35.96s.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removed unused files and rebuild✨  Done in 27.97s.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* refactore file structure build✨  Done in 29.86s.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding coverage reporter

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* Couldn't find a repository matching this job.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* trying to include coveralls, not sure how it works

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding - node

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding cov up to now only 30% of the code liness

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* updated the read me

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* coverage badge

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* testing enumerations

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* reducing testings

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* moving files outside the api folder to include tests

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* all features now implemented

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* index files for each folders must contain only exports

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* moving typescript our of core

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* updated scripts

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* moving folders around

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* configs mooved

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removing and moving some config files

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* installed  dependencies using yarn

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* FIX: error TS5058 specified path does not exist

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* refactoring test and output dir

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* FIX:  has no exported member 'testExamples'.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding utils tests

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* suspended test for now

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* will add testing soon...

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* running manual testing

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removing tokend and voiding it

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* ![Manual testing coverage](https://raw.githu
feature-axio-mock/images/manual-testing.png)

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* Manual testing coverage

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* manually tested and working

* Update README.md

* Update README.md

* spliting code into files

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* temp token to test the features (will be revoked)

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* asynck added

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* will revoke the token

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* import { Credentials } from '../../../typescript';

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding one test per functions

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* changing test suites of locations

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* open api to inject axios mock

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding tap into apiAxios to remplace with a mock

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding windo to tap into code and remplace axioss

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

*  _axiosApi  now built with an acess to change axios to mock jest

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* partialy adding mock axos support

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding axios support for jest mock test function

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* up to the top most level axios to mock with jest

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* spliting into diferent files

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removing un-usefull files from npm_modules

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* creating a test suite for the project

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* installed dependeciens again

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* types will be in typings folder

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* alowed export out of the package

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* canot use axios in jest testings

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* trying to revers top-down data flow to be down-top

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* moving usage to  _coreApiFunction instead

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* including IOptionChains

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* function return type annotations

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* will mutade output in ./build

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removing the many typescript folders

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* interface now defined in a d.ts file

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* changing back to normal ts files from .d.ts

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* changing output code removing _axiosapi funct

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removing any types keywords

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* ts(7006)

* doing some testing of new features

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* change stuff not yet ready for production

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* changes to tests

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* Next/features (#19)

* testing compatibility with interfaces and results

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding hash id discriminant to candels

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removing proto get hash function

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* first build: ✨in 50.17s.  next build: ✨in 45.00s.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* Update package.json

$ prettier --check --write --config .prettierrc './src/**/*.ts'
✨  Done in 6.25s.
$ tslint --project ./ --format codeFrame --fix
✨  Done in 11.38s.
$ tsc --noEmit --pretty
✨  Done in 8.98s.
$ concurrently "yarn:out:cjs" "yarn:out:umd" "yarn:out:amd" "yarn:out:sys"
✨  Done in 37.74s.
$ concurrently "rimraf ./build/src/test/__test__" "rimraf ./build/typings/test/__test__" "rimraf ./build/js/umd/src/test/__test__" "rimraf ./build/js/umd/typings/test/__test__;"
✨  Done in 2.42s.

* first ✨in 34.34s. then✨in 25.06s.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* forst ✨  Done in 31.52s. then ✨  Done in 21.50s.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* install

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* keywords

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* yarn install --force --audit --link-duplicates --check-files

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* + questrade-ts@1.0.0-rc7

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>