Version/feature axio mock (#18)
* splited axiosApi ✨  Done in 35.96s.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removed unused files and rebuild✨  Done in 27.97s.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* refactore file structure build✨  Done in 29.86s.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding coverage reporter

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* Couldn't find a repository matching this job.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* trying to include coveralls, not sure how it works

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding - node

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding cov up to now only 30% of the code liness

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* updated the read me

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* coverage badge

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* testing enumerations

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* reducing testings

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* moving files outside the api folder to include tests

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* all features now implemented

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* index files for each folders must contain only exports

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* moving typescript our of core

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* updated scripts

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* moving folders around

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* configs mooved

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removing and moving some config files

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* installed  dependencies using yarn

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* FIX: error TS5058 specified path does not exist

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* refactoring test and output dir

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* FIX:  has no exported member 'testExamples'.

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* adding utils tests

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* suspended test for now

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* will add testing soon...

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* running manual testing

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* removing tokend and voiding it

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* ![Manual testing coverage](https://raw.githu
feature-axio-mock/images/manual-testing.png)

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>

* Manual testing coverage

Signed-off-by: Benjamin Vincent <luxcium@neb401.com>